(#102)feat/random nickname
Team-Port/Voilio-Backend pull request #103
Opened 2023-10-17 16:24 UTC by wndjs803

## 추가/수정한 기능 설명
랜던 닉네임 생성 API입니다.
<br>

## check list
- [ ] issue number를 브랜치 앞에 추가 하였는가?
- [ ] 추가/수정사항을 설명하였는가?

2023-10-17 16:25 UTC, wndjs803 commented
형용사 5개, 명사 5개 조합으로 생성되는 랜덤 닉네임입니다.

2023-10-18 09:25 UTC, gilyeon00 requested changes

2023-10-18 09:25 UTC, gilyeon00 commented on src/main/java/com/techeer/port/voilio/domain/user/service/UserService.java
> +    String[] nounList = {"개발자", "댄서", "기획자", "CEO", "뮤지션"};
랜덤으로 나오는 거니까 직업군보다 동물/새/물고기 이름 등으로 하는게 더 좋을 것같습니다!!

2023-10-18 09:25 UTC, gilyeon00 commented on src/main/java/com/techeer/port/voilio/domain/user/service/UserService.java
> +    return nickname;
기존 DB에 있는 닉네임과 일치하지 않는지 유효성 체크 필요합니다 :)

2023-10-26 14:40 UTC, gilyeon00 commented
수고 많으셨습니다 :) 👍🏻👍🏻👍🏻👍🏻

2023-10-26 15:13 UTC, merged