feat: 프로필 이미지 변경 API
Team-Port/Voilio-Backend pull request #110
Opened 2023-10-26 12:51 UTC by wndjs803

## 추가/수정한 기능 설명

<br>

## check list
- [ ] issue number를 브랜치 앞에 추가 하였는가?
- [ ] 추가/수정사항을 설명하였는가?

2023-10-26 15:10 UTC, gilyeon00 commented
열심히 구현하신 것같아 수고하셨습니다 ㅠㅠ 근데..  image 를 s3 에 올리는 controller 는 이미 존재합니다 !
그래서 주언님께서는 프론트로부터 url (String) 으로 request 받으시면, 그걸 해당 user 의 정보에 업데이트 하는 로직을 구현하시면 됩니다
이미지 자체 올리는 것도 해본 거다 생각하시구 다시 만들어주시면 좋을 것같습니다 :-)

2023-10-27 12:11 UTC, gilyeon00 requested changes

2023-10-27 12:11 UTC, gilyeon00 commented on src/main/java/com/techeer/port/voilio/domain/user/dto/UserProfileDto.java
> +  @NotNull private String imageUrl;
String 만 return 해주는 거라면 Dto 만들지 않고 그냥 String 으로만 넘겨주셔도 됩니다 !

2023-10-27 12:11 UTC, gilyeon00 commented on src/main/java/com/techeer/port/voilio/domain/user/controller/UserController.java
> +  @PostMapping("/profileImage")
저희 URI 파라미터는 스네이크 케이스 쓰고있습니다 :)

2023-10-27 12:11 UTC, gilyeon00 commented on src/main/java/com/techeer/port/voilio/domain/user/service/UserService.java
> +
DB에 값 저장해주는 로직은 @Transaction 어노테이션 붙여주셔야합니다

2023-10-27 13:10 UTC, wndjs803 commented on src/main/java/com/techeer/port/voilio/domain/user/service/UserService.java
>    }
기존 로직에서는 아래와 같은 오류가 발생하였습니다.
A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: com.techeer.port.voilio.domain.user.entity.User.boards

제 개인적인 생각으로는 UserDto에 board에 관한 필드가 주석처리 되어 있어서 오류가 발생한 것 같습니다.
그래서 저는 DTO가 아닌 User 객체를 불러와 정보를 수정하는 방식으로 수정해 보았습니다.

2023-10-27 13:13 UTC, wndjs803 commented
UserService에 @Transactional에 readOnly = true 옵션이 빠져있는 이유도 궁금하고(일부러 안 넣으신 건지), deleteUser에도 @Transactional을 붙이는 것이 맞겠죠?

2023-10-27 14:01 UTC, gilyeon00 commented on src/main/java/com/techeer/port/voilio/domain/user/service/UserService.java
>    }
오오오 아주 굿굿입니당 !!!!!!!
이렇게 설명도 남겨주셔서 넘 좋은 것같아요 !!!

2023-10-27 14:03 UTC, gilyeon00 commented
UserService에 @transactional에 readOnly = true 옵션이 빠져있는 이유는.. 저 당시에 넣어야하는 지 몰랐거나 실수했거나 한 이유입니다 😅 캐치해주셔서 감사합니다 수고많으셨어요!

2023-10-27 14:16 UTC, merged